<?php

add_action( 'admin_menu', 'gds_gardens_add_settings_page' );
add_action( 'admin_init', 'gds_gardens_register_settings' );

/**
 *  To add menu option in dashboard
 */
function gds_gardens_add_settings_page() {
    add_submenu_page(
          'options-general.php',          // admin page slug
          __( 'Community Gardens API Integration', 'gds_geodatahub_gardens' ), // page title
          __( 'Community Gardens API Integration Menu', 'gds_geodatahub_gardens' ), // menu title
          'manage_options',               // capability required to see the page
          'gds_geodatahub_gardens_options', // admin page slug, e.g. options-general.php?page=wporg_options
          'gds_geodatahub_gardens_settings_page'            // callback function to display the options page
     );
}

/**
* Fetches array of links generated by WP Plugin admin page ( Deactivate | Edit )
* and inserts a link to the plugin settings
*
*/
function gds_gardens_settings_link( $links ) {
  return array_merge(
    array(
      'settings' => '<a href="' . admin_url( 'options-general.php?page=gds_geodatahub_gardens_options' ) . '">' . __( 'Settings' ) . '</a>',
      'source' => '<a href="https://github.com/Guelph-Digital-Service/gds-geodatahub-gardens"  target="_blank">' . __( 'Source Code' ) . '</a>'
    ),
    $links
  );
}
add_filter( 'plugin_action_links_' . plugin_basename( GDSGARDENS_FILE ), 'gds_gardens_settings_link' );

/**
 * Register the settings
 */
function gds_gardens_register_settings() {
     register_setting( 'gds_geodatahub_gardens_options', 'gds_geodatahub_gardens_genset' );
}

/**
 *  To add settings page
 *
 * @since Hide Featured Image 1.1
 */
function gds_geodatahub_gardens_settings_page() {
     if ( ! isset( $_REQUEST['settings-updated'] ) )
          $_REQUEST['settings-updated'] = false; ?>

     <div class="wrap gds-geodatahub-gardens">

          <h2><?php echo esc_html( get_admin_page_title() ); ?></h2>

          <div id="poststuff">
               <div id="post-body">
                    <div class="postbox-container column-primary">
                         <div id="hide_featured_setting" class="postbox">
                            <h2 class="hndle"><span>General Settings</span></h2>
                            <div class="inside">
                                 <form method="post" action="options.php">
                                      <?php settings_fields( 'gds_geodatahub_gardens_options' ); ?>
                                      <?php $gdsset = get_option( 'gds_geodatahub_gardens_genset' ); ?>
                                      <table class="form-table">
                                        <tr valign="top"><th scope="row"><?php _e( 'URL of API (the bit before `query?`):', 'gds_geodatahub_gardens' ); ?></th>
                                             <td>
                                                 <?php $apiurl = ( isset( $gdsset['api_url'] ) ) ? $gdsset['api_url'] : 0; ?>
                                                 <input id='gds_geodatahub_gardens_genset_api_url' name='gds_geodatahub_gardens_genset[api_url]' type='text' value='<?php echo $apiurl ?>' style='width:100%'/>
                                             </td>
                                         </tr>
                                         <tr valign="top"><th scope="row"><?php _e( 'Slug of community gardens parent page (defaults to home):', 'gds_geodatahub_gardens' ); ?></th>
                                              <td>
                                                  <?php $archparent = ( isset( $gdsset['archive_parent'] ) ) ? $gdsset['archive_parent'] : blah; ?>
                                                  <input id='gds_geodatahub_gardens_genset_archive_parent' name='gds_geodatahub_gardens_genset[archive_parent]' type='text' value='<?php echo $archparent ?>' style='width:100%'/>
                                              </td>
                                          </tr>
                                           <tr valign="top"><th scope="row"><?php _e( 'Show Garden Post-type on admin sidebar?', 'gds_geodatahub_gardens' ); ?></th>
                                                <td>
                                                    <?php $selected = ( isset( $gdsset['menu_show'] ) ) ? $gdsset['menu_show'] : 0; ?>
                                                    <input type="radio" name="gds_geodatahub_gardens_genset[menu_show]" value="1" <?php checked( $selected, 1 ); ?>><?php _e( 'Yes', 'gds_geodatahub_gardens' ); ?>&nbsp;&nbsp;
                                                    <input type="radio" name="gds_geodatahub_gardens_genset[menu_show]" value="0" <?php checked( $selected, 0 ); ?>><?php _e( 'No', 'gds_geodatahub_gardens' ); ?>
                                                </td>
                                            </tr>
                                      </table>
                                      <?php submit_button(); ?>
                                 </form>
                             </div>
                         </div>

                    </div> <!-- end post-body-content -->

                    <div class="postbox-container column-secondary">
                            <div id="hide_featured_donate" class="postbox">
                                <h2 class="hndle"><span><?php _e("Support this plugin", 'gds_geodatahub_gardens'); ?></span></h2>
                                <div class="inside">
                                    <p><?php printf(__(" This plugin was developed by %s Nic Durish %s as part of the %s Guelph Digital Service%s's mission to support the integration of City Services, systems, API's, and databases. Down with redundancy!", 'gds_geodatahub_gardens'), "<a href='https://nicdurish.ca' target='_blank'>", "</a>", "<a href='https://github.com/Guelph-Digital-Service' target='_blank'>", "</a>"); ?></p>
                                    <p><?php printf(__("For more information on contributing, usages, testing, or bug reporting, please visit this plugins %s Github Page %s", 'gds_geodatahub_gardens'), "<a href='https://github.com/Guelph-Digital-Service/gds-geodatahub-gardens' target='_blank'>", "</a>");?></p>
                                </div>
                            </div>
                    </div>
               </div> <!-- end post-body -->
          </div> <!-- end poststuff -->
     </div>
    <style>
       .gds-geodatahub-gardens #poststuff .column-primary {
        	width: 71%;
        	padding: 0;
        	float: left;
        }
        .gds-geodatahub-gardens #poststuff .column-secondary {
        	width: 28%;
        	float: right;
        	padding: 0;
        }
        .gds-geodatahub-gardens li {
            line-height: 1.4em;
        }
    </style><?php
}
